plugins {
    id 'java'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

dependencies {
    implementation 'org.bouncycastle:bcprov-jdk18on:1.86'
    implementation 'org.bouncycastle:bcpkix-jdk18on:1.86'
    testImplementation 'junit:junit:4.13.2'
}

tasks.register('runServer', JavaExec) {
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'ru.nsu.babich.server.ServerApplication'
}

tasks.register('runClient', JavaExec) {
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'ru.nsu.babich.client.ClientApplication'
    workingDir = projectDir
}
